version: '3.5'

services:
  elara:
    build: .
    container_name: elara
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - .:/var/www/html

  mysql:
    container_name: elaradb
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - db-data:/var/lib/mysql

  mysql-test:
    container_name: elaradb-test
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  redis:
    container_name: elara-redis
    image: redis:alpine
    ports:
      - "16379:6379"

volumes:
  db-data:
